---
- name: Converge
  hosts: all
  vars:
    vmalert_rule_files:
      - tests/victoria.yaml

  tasks:

    - name: "Include v98765_vm_single"
      include_role:
        name: "v98765_vm_single"

    - name: "Include v98765_vmalert"
      include_role:
        name: "v98765_vmalert"
